name: Create Tag on Version Bump
on: [ pull_request, push ]

jobs:
  createtag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: SebRollen/toml-action@v1.2.0
        id: read_toml
        with:
          file: 'Cargo.toml'
          field: 'package.version'

      - uses: rickstaa/action-create-tag@v1
        id: tag_create
        with:
          tag: "${{ steps.read_toml.outputs.value }}"
          tag_exists_error: false